---
# tasks file for wireguard_install
- name: Install wireguard
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop: "{{package_list}}"

- name: Update SystemCtl Settings
  sysctl:
    name: "{{item}}"
    value: '1'
    state: present
    reload: yes
  loop:
    - "net.ipv4.ip_forward"
#    - "net.ipv6.conf.all.forwarding = 1"
