---
# Packages need to be installed
package_list:
  - wireguard
  - iptables
  - resolvconf

# wireguard parameters
wg_conf_dir: /etc/wireguard
public_ip: "{{ansible_default_ipv4.address}}"  #hostvars[inventory_hostname]['ansible_default_ipv4']['address']
public_nic: "{{ansible_default_ipv4.interface}}"
wg_nic: wg0
wg_ipv4: 172.16.16.1 #10.66.66.1
wg_port: 51094
